language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
script: python manage.py test
